src/main/java/net/anvas/usercontroller/model/User.java
package net.anvas.usercontroller.model;

import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * Created by andrey on 16.11.16.
 */
@Entity
@Table(name = "User")
public class User implements Serializable{
    private static final long serialVersionUID = 1L;
    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Column(name = "name")
    private String name;

    @Column(name = "age")
    private int age;

    @Column(name = "isAdmin")
    private boolean isAdmin;

    @Column(name = "createDate")
    @Temporal(value=TemporalType.DATE)
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date createDate;

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", age=" + age +
                ", isAdmin=" + isAdmin +
                ", createDate=" + createDate +
                '}';
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public boolean isAdmin() {
        return isAdmin;
    }

    public void setAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof User)) return false;

        User user = (User) o;

        if (id != user.id) return false;
        if (age != user.age) return false;
        if (isAdmin != user.isAdmin) return false;
        if (!name.equals(user.name)) return false;
        return createDate != null ? createDate.equals(user.createDate) : user.createDate == null;

    }

    @Override
    public int hashCode() {
        int result = id;
        result = 31 * result + name.hashCode();
        result = 31 * result + age;
        result = 31 * result + (isAdmin ? 1 : 0);
        result = 31 * result + (createDate != null ? createDate.hashCode() : 0);
        return result;
    }
}

src/main/java/net/anvas/usercontroller/controller/UserController.java
package net.anvas.usercontroller.controller;

import net.anvas.usercontroller.model.User;
import net.anvas.usercontroller.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.util.Date;

/**
 * Created by andrey on 16.11.16.
 */
@Controller
public class UserController {
    private static final int LINE_BY_PAGE=10;

    private UserService userService;

    @Autowired(required = true)
    @Qualifier(value = "userService")
    public void setUserService(UserService userService) {
        this.userService = userService;
    }

    @RequestMapping(value = "users", method = RequestMethod.GET)
    public String getAllUsers(@RequestParam(value = "page", required = false) Integer page,
                              @RequestParam(value = "userName", required = false) String userName, Model model){
        userName = userName == null ? "" : userName;
        Integer lastPage = (this.userService.getUsersCount(userName)-1) / LINE_BY_PAGE + 1;
        page = page ==null ? 1 : page > lastPage ? lastPage : page;
        Integer startPage = page-2 > 0 ? page-2:1;
        Integer endPage = startPage+4 < lastPage ? startPage+4:lastPage;
        startPage = endPage-4 > 0 ? endPage-4:1;
        model.addAttribute("linebypage", LINE_BY_PAGE);
        model.addAttribute("startPage", startPage);
        model.addAttribute("endPage", endPage);
        model.addAttribute("lastPage", lastPage);
        model.addAttribute("page", page);
        model.addAttribute("userName", userName);
        model.addAttribute("user", new User());
        String filter="";
        if (!userName.equals("")){
            filter="where name like '%"+userName+"%'";
        }
        model.addAttribute("listUsers", this.userService.getAllUsers(filter, page-1, LINE_BY_PAGE));

        return "users";
    }

    @RequestMapping(value = "/users/add", method = RequestMethod.POST)
    public String addUser(@ModelAttribute("user") @DateTimeFormat(pattern = "yyyy-MM-dd") User user,
                          @RequestParam(value = "page", required = false) Integer page,
                          @RequestParam(value = "userName", required = false) String userName){
        userName = userName == null ? "" : userName;
        Integer lastPage = (this.userService.getUsersCount(userName)-1) / LINE_BY_PAGE + 1;
        page = page ==null ? 1 : page > lastPage ? lastPage : page;
        if(user.getId() == 0){
            user.setCreateDate(new Date());
            this.userService.addUser(user);
        }else  {
            this.userService.updateUser(user);
        }

        return "redirect:/users?page="+page+"&userName="+userName;
    }

    @RequestMapping("/remove")
    public String removeUser(@RequestParam(value = "id") int id,
                             @RequestParam(value = "page", required = false) Integer page,
                             @RequestParam(value = "userName", required = false) String userName){
        userName = userName == null ? "" : userName;
        Integer lastPage = (this.userService.getUsersCount(userName)-1) / LINE_BY_PAGE + 1;
        page = page ==null ? 1 : page > lastPage ? lastPage : page;
        this.userService.removeUser(id);

        return "redirect:/users?page="+page+"&userName="+userName;
    }

    @RequestMapping("/edit")
    public String editUser(@RequestParam(value = "id") int id,
                           @RequestParam(value = "page", required = false) Integer page,
                           @RequestParam(value = "userName", required = false) String userName, Model model) {
        userName = userName == null ? "" : userName;
        int lastPage = (this.userService.getUsersCount(userName)-1) / LINE_BY_PAGE + 1;
        page = page == null ? 1 : page > lastPage ? lastPage : page;
        int startPage = page-2 > 0 ? page-2:1;
        int endPage = startPage+4 < lastPage ? startPage+4:lastPage;
        startPage = endPage-4 > 0 ? endPage-4:1;
        model.addAttribute("linebypage", LINE_BY_PAGE);
        model.addAttribute("startPage", startPage);
        model.addAttribute("endPage", endPage);
        model.addAttribute("lastPage", lastPage);
        model.addAttribute("page", page);
        model.addAttribute("userName", userName);
        model.addAttribute("user", this.userService.getUserById(id));
        String filter="";
        if (!userName.equals("")){
            filter="where name like '%"+userName+"%'";
        }
        model.addAttribute("listUsers", this.userService.getAllUsers(filter, page-1,LINE_BY_PAGE));

        return "users";
    }
}

src/main/webapp/WEB-INF/pages/users.jsp
<%--
  Created by IntelliJ IDEA.
  User: andrey
  Date: 17.11.16
  Time: 12.11
  To change this template use File | Settings | File Templates.
--%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib prefix="from" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ page session="false" %>
<html>
<head>
    <title>User </title>

    <style type="text/css">
        .tg {
            border-collapse: collapse;
            border-spacing: 0;
            border-color: #ccc;
        }

        .tg td {
            font-family: Arial, sans-serif;
            font-size: 14px;
            padding: 5px 5px;
            height: 27px;
            border-style: solid;
            border-width: 1px;
            overflow: hidden;
            word-break: normal;
            border-color: #ccc;
            color: #333;
            background-color: #fff;
        }

        .tg th {
            font-family: Arial, sans-serif;
            font-size: 14px;
            font-weight: normal;
            padding: 10px 5px;
            border-style: solid;
            border-width: 1px;
            overflow: hidden;
            word-break: normal;
            border-color: #ccc;
            color: #333;
            background-color: #f0f0f0;
        }

        .tg .tg-4eph {
            background-color: #f9f9f9
        }

        .pagination p{
            border-collapse: collapse;
            border-spacing: 0;
            font-family: Arial, sans-serif;
            font-size: 16px;
            font-weight: normal;
            text-decoration: none;
            text-indent: 25px;

        }
        .pagination a{
            color: #191970;
            text-decoration: none;
        }

        .pagination p .activePage a {
            color: #8B0000;
        }

        .pagination p .noActiveEl{
            color: #828178;
        }
    </style>
</head>
<body>
<a href="../../index.jsp">Back to main menu</a>

<br/>
<br/>

<h1>User list</h1>

<c:url var="getAllUsersAction" value="/users"/>

<table border = "0">
    <tr>
        <td><b>User name</b></td>
            <form name = "listUsr" action="${getAllUsersAction}" method="get">
                <td>
                    <input type = "text" name = "userName" value = "${userName}" size = "25"/>
                </td>
                <td ><input type = "submit" value = "Find"/></td>
            </form>
            <form action="${getAllUsersAction}">
                <td>
                    <input type = "hidden" name = "page" value = "${page}"/>
                    <button type="submit">Clear</button>
                </td>
            </form>
    </tr>
</table>


    <table class="tg">
        <tr>
            <th width="20">ID</th>
            <th width="200">Name</th>
            <th width="30">Age</th>
            <th width="5">Admin</th>
            <th width="120">Create date</th>
            <th width="60">Edit</th>
            <th width="60">Delete</th>
        </tr>
        <c:forEach var="line" begin="0" end="${linebypage-1}">
            <c:if test="${listUsers.size()>line}">
                <c:set var="usr" value="${listUsers.get(line)}"/>
                <tr>
                    <td>${usr.id}</td>
                    <td>${usr.name}</td>
                    <td>${usr.age}</td>
                    <td>${usr.admin}</td>
                    <td>${usr.createDate}</td>
                    <td><a href="<c:url value='/edit?id=${usr.id}&page=${page}&userName=${userName}'/>">Edit</a></td>
                    <td><a href="<c:url value='/remove?id=${usr.id}&page=${page}&userName=${userName}'/>">Delete</a></td>
                </tr>
            </c:if>
            <c:if test="${listUsers.size()<=line}">
                <tr>
                    <td> </td>
                    <td> </td>
                    <td> </td>
                    <td> </td>
                    <td> </td>
                    <td> </td>
                    <td> </td>
                </tr>
            </c:if>
        </c:forEach>
    </table>

    <div class="pagination">
        <p>
                <c:if test="${page==1}">
                    <span class="noActiveEl">prew .. </span>
                </c:if>
                <c:if test="${page>1}">
                    <a href="<c:url value="/users" >
                        <c:param name="page" value="${page-1}"/>${page-1}
                        <c:param name="userName" value="${userName}"/>${userName}
                        </c:url>">
                        prew ..
                    </a>
                </c:if>
                <c:forEach begin="${startPage}" end="${startPage+4}" var="p">
                    <c:if test="${p==page}">
                        <span class="activePage">
                    </c:if>
                    <c:if test="${p<=endPage}">
                        <a href="<c:url value="/users" >
                            <c:param name="page" value="${p}"/>${p}
                            <c:param name="userName" value="${userName}"/>${userName}
                            </c:url>"> ${p} </a>
                    </c:if>
                    <c:if test="${p>endPage}">
                        <span class="noActiveEl"> ${p} </span>
                    </c:if>
                    <c:if test="${p==page}">
                        </span>
                    </c:if>

                </c:forEach>
                <c:if test="${page==lastPage}">
                    <span class="noActiveEl"> .. next</span>
                </c:if>
                <c:if test="${page<lastPage}">
                    <a href="<c:url value="/users" >
                        <c:param name="page" value="${page+1}"/>${page+1}
                            <c:param name="userName" value="${userName}"/>${userName}
                            </c:url>">
                        .. next
                    </a>
                </c:if>
        </p>
    </div>



<h1>Add / Edit a User</h1>

<c:url var="addAction" value="/users/add"/>

<form:form action="${addAction}" commandName="user">
    <input type="hidden" name = "page" value="${page}"/>
    <input type="hidden" name = "userName" value="${userName}"/>
    <table>
        <c:if test="${!empty user.name}">
            <tr>
                <td>
                    <form:label path="id">
                        <spring:message text="ID"/>
                    </form:label>
                </td>
                <td>
                    <form:input path="id" readonly="true" size="8" disabled="true"/>
                    <form:hidden path="id"/>
                </td>
            </tr>
        </c:if>
        <tr>
            <td>
                <form:label path="name">
                    <spring:message text="Name"/>
                </form:label>
            </td>
            <td>
                <form:input path="name"/>
            </td>
        </tr>
        <tr>
            <td>
                <form:label path="age">
                    <spring:message text="Age"/>
                </form:label>
            </td>
            <td>
                <form:input path="age"/>
            </td>
        </tr>
        <tr>
            <td>
                <form:label path="admin">
                    <spring:message text="Admin"/>
                </form:label>
            </td>
            <td>
                <form:select path="admin">
                    <form:option value="false">false</form:option>
                    <form:option value="true">true</form:option>
                </form:select>
            </td>
        </tr>
        <c:if test="${!empty user.name}">
            <tr>
                <td>
                    <form:label path="createDate">
                        <spring:message text="Create date"/>
                    </form:label>
                </td>
                <td>
                    <form:input type = "date" path="createDate" readonly="true" size="8" disabled="true"/>
                    <form:hidden path="createDate"/>
                </td>
            </tr>
        </c:if>
        <tr>
            <td colspan="2">
                <c:if test="${!empty user.name}">
                    <input type="submit"
                           value="<spring:message text="Save"/>"/>
                </c:if>
                <c:if test="${empty user.name}">
                    <input type="submit"
                           value="<spring:message text="Add User"/>"/>
                </c:if>
            </td>
        </tr>
    </table>
</form:form>

</body>
</html>

src/main/webapp/index.jsp
<%--
  Created by IntelliJ IDEA.
  User: andrey
  Date: 17.11.16
  Time: 12.08
  To change this template use File | Settings | File Templates.
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>User Editor</title>
</head>
<body>
<h2>Test task for JavaRush (CRUD)</h2>
<h3>User editor</h3>
<br/>
<a href="<c:url value="/users"/>" target="_self">Click to edit "User list"</a>
<br/>
</body>
</html>